version: "3.8"

services:
  # Definiert die Python-Anwendung, die Logs erzeugt.
  python-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "5002:5002"
    environment:
      - OTEL_SERVICE_NAME=python-app
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      # Stellt sicher, dass die auto-instrumentierten Metriken per OTLP gesendet werden
      - OTEL_METRICS_EXPORTER=otlp
      # Sagt der Auto-Instrumentierung, dass sie auch das Logging übernehmen soll
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      # Stellt sicher, dass die erfassten Logs per OTLP gesendet werden
      - OTEL_LOGS_EXPORTER=otlp
    networks:
      - monitoring-net

  # Definiert Grafana und konfiguriert beim Start automatisch Loki als Datenquelle.
  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
        - grafana-data:/var/lib/grafana
        # Wir lagern die Konfiguration in eine eigene Datei aus, um Syntaxfehler zu vermeiden
        - ./grafana-provisioning/:/etc/grafana/provisioning/
      networks:
        - monitoring-net
      depends_on:
        - loki
        - tempo

  # Definiert Loki, den Dienst zum Speichern der Logs.
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitoring-net

  # Definiert Tempo, den Dienst zum Speichern der Traces.
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo-config.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo-config.yaml
    ports:
      - "3200:3200"
    networks:
      - monitoring-net

  # Definiert Alloy, den Agenten zum Sammeln und Weiterleiten der Logs an Loki.
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - python-app
      - loki
      - tempo
    networks:
      - monitoring-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # Dadurch öffnet Prometheus den Endpunkt /api/v1/write, den Alloy zum Senden der Metriken verwendet.
      # Das ist notwendig, damit die custom metrics, die wir mit otel in app.py erstellen, bei Prometheus landen.
      - --web.enable-remote-write-receiver
    networks:
      - monitoring-net

# Definiert das gemeinsame virtuelle Netzwerk für alle Dienste.
networks:
  monitoring-net:
    driver: bridge

# Definiert das benannte Volume für die dauerhafte Speicherung von Grafana-Daten.
volumes:
  grafana-data:
